title: oleksis | Who I am
description: > # this means to ignore newlines until "show_excerpts:"
  Oleksis @ GitHub

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    - { platform: rss, user_url: "/feed.xml" }
    - { platform: github, user_url: "https://github.com/oleksis/" }
    - { platform: twitter, user_url: "https://twitter.com/oleksis" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/oleksis/" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - releases.md

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
